version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: cmr_app_container
        image: alexabuharb/cmr_app
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        environment:
            - DB_HOST=mysql
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel
            - DB_PASSWORD=secret
        networks:
            - laravel
        depends_on:
            - mysql

    webserver:
        image: nginx:alpine
        container_name: nginx_webserver
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel
        depends_on:
            - app

    mysql:
        image: mysql:5.7
        container_name: laravel_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    mysql_data:
