# Use Nginx Alpine as base image
FROM nginx:alpine

# Update package lists and install apache2-utils
#RUN apk update \ apk add --no-cache apache2-utils

# Create directory for authentication file
RUN mkdir -p /etc/nginx/auth

# Generate .htpasswd file
#RUN htpasswd -cb /etc/nginx/auth/.htpasswd alex alex123


# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
