version: '3.8'
services:
    app:
        ports:
<<<<<<< HEAD
            - "9002:9000"
=======
            - "9000:9000"
>>>>>>> c61dc7371eb65f358cd1056852f967c8bb1f1f94
        build:
            context: .
            dockerfile: Dockerfile
        image: alexabuharb/cmr_app
        container_name: app_container
        restart: unless-stopped
        tty: true
        volumes:
            - .:/var/www/html
#        environment:
#            - DB_HOST=db
#            - DB_DATABASE=laravel
#            - DB_USERNAME=root
#            - DB_PASSWORD=root
        networks:
            - laravel
        depends_on:
            - db


    webserver:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        container_name: nginx_container
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./nginx_htpasswd:/etc/nginx/auth/.nginx_htpasswd
            - ./cloudflare-origin.key:/etc/nginx/ssl/cloudflare-origin.key
            - ./cloudflare-origin.crt:/etc/nginx/ssl/cloudflare-origin.crt
        networks:
            - laravel
        depends_on:
            - app


    db:
        image: mysql:5.7
        container_name: mysql_container
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    mysql_data:
